### ISSUE TITLE
Using GPTs

### ISSUE THREAD

**Issue by BlueFalconHD** [LunaHD24/ChatGPT-Wiki#1]
OpenAI introduced a [new feature called GPTs](https://openai.com/blog/introducing-gpts) which allow you to create "custom" versions of ChatGPT for specific use cases. 

---

They provide some really useful functionality:

### Uploading files
You can upload files that the GPT can access and reference.

### Actions
Actions serve as custom queries the GPT can perform, using an [OpenAPI Schema](https://swagger.io/specification/). It can then utilize the resulting output in whatever fashion necessary.

### Prompts
This is a pretty simple one, but you can provide the GPT a base prompt on how it will behave, and it works really well. There is also a "GPT Builder" which is a GPT made to generate prompts for GPTs (I know, confusing) but I prefer not using it. It really only works for very generalized goals.

### Tools
The GPT has toggleable access to:

#### Browse the web
The GPT can interact with a website (scroll down, up, click, type, etc.) and even search Bing.

#### Use DALLE
The GPT can also generate images using DALLE, the use of this is out of the scope of this issue.

#### Use the Data Analysis Environment
This is probably the most useful and important one. The GPT can either generate its own python code or run any provided, and get the output. It can read/use any uploaded files as well.

---

Also, the GPT's ability to use responses to further train ChatGPT can be disabled, to prevent leaking any data.

One issue is that currently [GPTs are limited to ChatGPT Plus subscribers](https://www.zdnet.com/article/ready-to-sign-up-for-chatgpt-plus-join-the-club-er-waitlist/). This means you cannot test unless you pay OpenAI $20 a month, and the ability signing up for the subscription is paused so OpenAI can fix some scaling issues.

---

I have tried this with technical stuff like commands and the results vary, but I know exactly what to do to improve them. I used Pandoc to convert the Mediawiki files to Markdown, and joined all of them in one file (I am not aware of a file size limit, but it  appears 10 files is the max). If I instead used an organized format, like JSON, I could use a script to fetch the relevant article so ChatGPT isn't reading through a 7mb file.

**Comment by LunaHD24** [comment]
Well, I guess I didn't _totally_ waste one hour of my life creating this :,)
These GPTs sound really useful, I'll try to take a look into them, but that relies on other people as I don't have ChatGPT Plus.
Thank you for this info :)

**Comment by BlueFalconHD** [comment]
I can help these for you, I have it.

**Comment by LunaHD24** [comment]
Nice, thank you. Do you know if you it's possible to get an API-Key to a custom GPT?

**Comment by BlueFalconHD** [comment]
Nope. It's like a list of GPTs to pick from and they make new chats, that are identical to the regular thing, apart from their behavior. 

Edit: I just realized what your question was referring to, don't think they implemented it yet, but they might soon.
